name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup Development Environment
        uses: jdx/mise-action@v2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Zola
        run: zola build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v4
